services:
  vite:
    image: node:19-alpine3.16
    working_dir: $PWD
    user: node
    init: true
    command: sh -c 'npm install && npm run dev'
    ports: 
      - 5173:5173
    volumes:
      - .:/$PWD

  cohost-feed:
    image: alpine:3.17.0
    command: wget https://cohost.org/jmsfbs/rss/public.json -O cohost.json; sleep infinity;
    working_dir: $PWD/static/feed
    user: "${UID}:${GID}"
    volumes:
      - .:/$PWD