name: Fly Deploy
on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '* 6 * * *'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: wget https://cohost.org/jmsfbs/rss/public.json ./static/feed/cohost.json
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only